import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 10,
  },
  headerGradient: {
    width: '100%',
    height: '100%',
    position: 'absolute',
  },
  headerImageContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerIcon: {
    opacity: 0.9,
  },
  titleContainer: {
    alignItems: 'center',
    marginVertical: 20,
    paddingHorizontal: 10,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 10,
    fontStyle: 'italic',
  },
  instructionCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 12,
    padding: 20,
    marginVertical: 10,
    borderWidth: 1,
    borderColor: 'rgba(200, 200, 200, 0.3)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  paragraph: {
    fontSize: 16,
    lineHeight: 24,
    marginTop: 10,
  },
  preguntaContainer: {
    marginTop: 10,
    marginBottom: 24,
    padding: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(200, 200, 200, 0.2)',
  },
  chatBubbleAssistant: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  avatarIcon: {
    marginRight: 14,
    marginTop: 4,
  },
  bubbleContent: {
    flex: 1,
  },
  preguntaText: {
    fontSize: 16,
    marginBottom: 8,
    fontWeight: '500',
  },
  categoria: {
    marginTop: 4,
    marginBottom: 4,
    fontStyle: 'italic',
    fontSize: 13,
    opacity: 0.8,
  },
  opcionesContainer: {
    marginTop: 20,
    paddingHorizontal: 8,
  },
  opcion: {
    marginVertical: 6,
    paddingVertical: 14,
    paddingHorizontal: 18,
    borderRadius: 10,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  opcionTexto: {
    fontWeight: '500',
    fontSize: 15,
  },
  loadingContainer: {
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  emptyContainer: {
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  contadorContainer: {
    marginTop: 24,
    marginBottom: 8,
    padding: 8,
    alignItems: 'center',
  },
  contadorBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#4A90E2',
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 16,
  },
  contadorText: {
    color: '#FFFFFF',
    fontWeight: '500',
    fontSize: 14,
  },
  progressContainer: {
    marginBottom: 24,
    padding: 8,
  },
  progressHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  progressText: {
    fontSize: 14,
    opacity: 0.8,
  },
  progressBar: {
    height: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 3,
    marginTop: 8,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 3,
  },
  navigationButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 30,
    paddingHorizontal: 8,
    marginBottom: 20,
  },
  navButton: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    backgroundColor: '#333333', // Gris oscuro para botones activos
    minWidth: 120,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  disabledButton: {
    backgroundColor: '#555555', // Gris un poco más claro o con más transparencia para deshabilitados
    opacity: 0.7,
  },
  navButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 15,
  },
  // Estilos para el Modal de Resultados
  modalCenteredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.6)', // Fondo semitransparente
  },
  modalView: {
    margin: 20,
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    width: '90%',
    maxWidth: 400,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 20,
    textAlign: 'center',
  },
  resultadoItemContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#eee', // Un color claro para el separador
  },
  resultadoPartidoNombre: {
    fontSize: 17,
    fontWeight: '500',
  },
  resultadoAfinidad: {
    fontSize: 17,
    fontWeight: 'bold',
  },
  partidoMasAfin: {
    marginTop: 25,
    fontSize: 16,
    textAlign: 'center',
    lineHeight: 24,
  },
  buttonClose: {
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 30,
    elevation: 2,
    marginTop: 25,
  },
  textStyleButton: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 16,
  },
  // Nuevos estilos para la vista de resultados directos
  resultadosViewContainer: {
    marginTop: 20,
    marginBottom: 20,
    padding: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.08)', // Un fondo sutil
    borderRadius: 15,
    borderWidth: 1,
    borderColor: 'rgba(200, 200, 200, 0.25)',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 4,
  },
  resultadosTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 15,
    textAlign: 'center',
  },
  resultadosSubTitle: {
    fontSize: 18,
    textAlign: 'center',
    marginBottom: 20,
    fontStyle: 'italic',
    opacity: 0.9,
  },
  resultadoIndividualContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(200, 200, 200, 0.15)', // Separador más sutil
  },
  resultadoPartido: {
    fontSize: 18,
    fontWeight: '500',
  },
  resultadoPorcentaje: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  agradecimientoText: {
    fontSize: 16,
    textAlign: 'center',
    marginTop: 25,
    marginBottom: 15,
    lineHeight: 24,
  },
  reiniciarButton: { // Estilo similar a navButton pero podría ser diferente si se desea
    paddingVertical: 14,
    paddingHorizontal: 25,
    borderRadius: 10,
    backgroundColor: '#4A90E2', // Un color distintivo para reiniciar
    minWidth: 180,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10, // Espacio antes del botón de reiniciar
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  reiniciarButtonText: { // Estilo similar a navButtonText
    color: 'white',
    fontWeight: 'bold',
    fontSize: 16,
  },
});
